import type { Metadata } from "next";
import { Lato} from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";

const lato = Lato({
  subsets: ["latin"],
  weight: "400"
});

export const metadata: Metadata = {
  title: "Global Impact Bible Church",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body className={lato.className}>
          <Providers>
            {children}
          </Providers>
        </body>
    </html>
  );
}
